import { builtinModules } from "module";
import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import * as sass from "sass";
import { execFile, execFileSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const STYLE_SOURCE = "styles.scss";
const STYLE_OUTPUT = "styles.css";

function compileStyles() {
	const result = sass.compile(STYLE_SOURCE, { style: "expanded" });
	fs.writeFileSync(STYLE_OUTPUT, result.css);
	console.log(`Compiled ${STYLE_SOURCE} to ${STYLE_OUTPUT}`);
}

// Replaces @protobufjs/inquire (which uses eval() to hide an optional require()
// from bundlers) with a stub that always returns null. The optional modules it
// probes for (buffer, long, fs) are not used in this codebase, and removing the
// eval avoids a false-positive flag from the Obsidian community directory review.
const stubInquirePlugin = {
	name: 'stub-protobufjs-inquire',
	setup(build) {
		build.onResolve({ filter: /^@protobufjs\/inquire$/ }, args => ({
			path: args.path,
			namespace: 'stub-inquire',
		}));
		build.onLoad({ filter: /.*/, namespace: 'stub-inquire' }, () => ({
			contents: 'module.exports = function inquire() { return null; };',
			loader: 'js',
		}));
	},
};

// Keep optional protobufjs/sax Node probes on their browser paths. Obsidian logs
// bare `fs`/`stream` probes before the libraries can catch the failed require.
const PROBING_MODULE = /[\\/](@?protobufjs|sax)[\\/]/;

const stubOptionalNodePlugin = {
	name: 'stub-optional-node-requires',
	setup(build) {
		build.onResolve({ filter: /^(fs|stream)$/ }, args => {
			if (!PROBING_MODULE.test(args.importer)) return null;
			return { path: args.path, namespace: 'stub-node' };
		});
		build.onLoad({ filter: /.*/, namespace: 'stub-node' }, () => ({
			contents: 'module.exports = {};',
			loader: 'js',
		}));
	},
};

const PLUGIN_ID = JSON.parse(fs.readFileSync("manifest.json", "utf8")).id;

// Load OBSIDIAN_PATH from .env (path to your vault's plugins folder, relative
// to $HOME, e.g. /Documents/Log/.obsidian/plugins). The plugin's own folder is
// appended automatically. Optional: without a .env, `npm run dev` just builds
// main.js in place, as it always has.
function loadEnv() {
	try {
		const raw = fs.readFileSync(".env", "utf8");
		for (const line of raw.split("\n")) {
			const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$/i);
			if (!m) continue;
			let val = m[2].trim();
			if ((val.startsWith('"') && val.endsWith('"')) ||
				(val.startsWith("'") && val.endsWith("'"))) {
				val = val.slice(1, -1);
			}
			process.env[m[1]] = val;
		}
	} catch (e) {
		if (e.code !== "ENOENT") throw e;
	}
}

// Vault name = the folder that contains .obsidian in OBSIDIAN_PATH (used to
// target the right vault when reloading via the Obsidian CLI).
function vaultName() {
	const parts = (process.env.OBSIDIAN_PATH || "").split("/").filter(Boolean);
	const i = parts.indexOf(".obsidian");
	return i > 0 ? parts[i - 1] : undefined;
}

// Ask Obsidian to hot-reload the plugin, so changes appear without a manual
// toggle. Requires the `obsidian` CLI on PATH; silently skipped if absent.
function reloadPlugin() {
	const vault = vaultName();
	// The CLI ignores vault= unless it is the first argument.
	const args = vault
		? [`vault=${vault}`, "plugin:reload", `id=${PLUGIN_ID}`]
		: ["plugin:reload", `id=${PLUGIN_ID}`];
	execFile("obsidian", args, (err, stdout) => {
		if (err) console.warn(`Skipped plugin reload: ${err.message}`);
		else console.log((stdout || "").trim() || `Reloaded: ${PLUGIN_ID}`);
	});
}

// Type-check before pushing, so a broken intermediate save (which esbuild
// happily bundles by stripping types) can't be copied in and disable the plugin
// on reload.
// Incremental, so repeat checks on a watch rebuild reuse the previous run's
// results instead of re-checking the whole project each save.
const TSC_ARGS = [
	"--skipLibCheck",
	"--incremental",
	"--tsBuildInfoFile",
	"node_modules/.cache/tsc.tsbuildinfo",
];

function typeChecks() {
	try {
		execFileSync("node_modules/.bin/tsc", TSC_ARGS, { stdio: "pipe" });
		return true;
	} catch (e) {
		const out = `${e.stdout || ""}${e.stderr || ""}`.trim();
		console.warn(`Skipped vault copy: type errors\n${out}`);
		return false;
	}
}

// Refresh CSS without reloading the plugin and closing its active screen.
const STYLE_NEEDLE = 'mod-importer';

function refreshStyles() {
	const code = [
		'(async () => {',
		`const dir = app.plugins.plugins[${JSON.stringify(PLUGIN_ID)}]?.manifest.dir;`,
		'if (!dir) return "no-plugin";',
		'const styleEl = Array.from(document.head.querySelectorAll(\'style[type="text/css"]\'))',
		`.find(el => el.textContent.includes(${JSON.stringify(STYLE_NEEDLE)}));`,
		'if (!styleEl) return "no-style";',
		'styleEl.textContent = await app.vault.readRaw(dir + "/styles.css");',
		'return "ok";',
		'})()',
	].join(' ');

	const vault = vaultName();
	const args = vault ? [`vault=${vault}`, 'eval', `code=${code}`] : ['eval', `code=${code}`];

	execFile('obsidian', args, (err, stdout) => {
		if (err || !`${stdout}`.includes('ok')) {
			reloadPlugin();
			return;
		}
		console.log('Updated styles.css in place');
	});
}

// Copy the built plugin files into the vault after each rebuild, then reload.
// styles.css matters as much as main.js here: the importer's modal UI is
// entirely styled from it.
function copyToVault({ reload = true } = {}) {
	if (!process.env.OBSIDIAN_PATH || !process.env.HOME) return;
	const dest = path.join(process.env.HOME, process.env.OBSIDIAN_PATH, PLUGIN_ID);
	try {
		fs.mkdirSync(dest, { recursive: true });
		for (const file of [outfile, "manifest.json", STYLE_OUTPUT]) {
			if (fs.existsSync(file)) {
				fs.copyFileSync(file, path.join(dest, path.basename(file)));
			}
		}
		console.log(`Copied plugin to ${dest}`);
		if (reload) reloadPlugin();
		else refreshStyles();
	} catch (e) {
		console.warn(`Skipped vault copy: ${e.message}`);
	}
}

// Poll these files because styles.scss is outside esbuild's dependency graph.
// A native directory watcher can exceed the file-handle limit alongside
// esbuild's watcher in larger development environments.
function watchSourceFiles() {
	let queued;
	let reload = false;
	let stylesChanged = false;

	function queueUpdate() {
		clearTimeout(queued);
		queued = setTimeout(() => {
			if (stylesChanged) {
				stylesChanged = false;
				try {
					compileStyles();
				} catch (e) {
					console.warn(`Skipped style update: ${e.message}`);
					return;
				}
			}
			copyToVault({ reload });
			reload = false;
		}, 100);
	}

	fs.watchFile(STYLE_SOURCE, { interval: 250 }, (current, previous) => {
		if (current.mtimeMs === previous.mtimeMs) return;
		stylesChanged = true;
		queueUpdate();
	});

	if (process.env.OBSIDIAN_PATH && process.env.HOME) {
		fs.watchFile("manifest.json", { interval: 250 }, (current, previous) => {
			if (current.mtimeMs === previous.mtimeMs) return;
			reload = true;
			queueUpdate();
		});
	}
}

const copyPlugin = {
	name: "copy-to-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length) return;
			if (!typeChecks()) return;
			copyToVault();
		});
	},
};

loadEnv();
compileStyles();

let outfile = "main.js";
if (fs.existsSync('./.devtarget')) {
	outfile = path.join(fs.readFileSync('./.devtarget', 'utf8').trim(), outfile);
	console.log('Temporary output location:', outfile);
}


const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],

	// We don't need to include code to create zip files (deflate), only read them (inflate),
	// so this cuts it out and makes the final bundle smaller.
	alias: {'@zip.js/zip.js': '@zip.js/zip.js/lib/zip-no-worker-inflate.js'},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	platform: 'browser',
	treeShaking: true,
	plugins: prod
		? [stubInquirePlugin, stubOptionalNodePlugin]
		: [stubInquirePlugin, stubOptionalNodePlugin, copyPlugin],
	outfile,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	watchSourceFiles();
}
