import { builtinModules } from "module";
import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import { execFile, execFileSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Replaces @protobufjs/inquire (which uses eval() to hide an optional require()
// from bundlers) with a stub that always returns null. The optional modules it
// probes for (buffer, long, fs) are not used in this codebase, and removing the
// eval avoids a false-positive flag from the Obsidian community directory review.
const stubInquirePlugin = {
	name: 'stub-protobufjs-inquire',
	setup(build) {
		build.onResolve({ filter: /^@protobufjs\/inquire$/ }, args => ({
			path: args.path,
			namespace: 'stub-inquire',
		}));
		build.onLoad({ filter: /.*/, namespace: 'stub-inquire' }, () => ({
			contents: 'module.exports = function inquire() { return null; };',
			loader: 'js',
		}));
	},
};

// protobufjs and sax probe for `fs` and `stream` with a bare require, each
// guarded by a try/catch and a fallback for when the module is absent. Obsidian
// logs "Attempting to load NodeJS package" before that catch runs, so loading
// the plugin printed a stack trace per probe for features neither library is
// used for here (reading a .proto off disk; sax's stream API). Answering with an
// empty module leaves each library on the browser path it already has. Our own
// node access goes through src/filesystem.ts, which asks for `node:fs` and is
// not what this matches.
const PROBING_MODULE = /[\\/](@?protobufjs|sax)[\\/]/;

const stubOptionalNodePlugin = {
	name: 'stub-optional-node-requires',
	setup(build) {
		build.onResolve({ filter: /^(fs|stream)$/ }, args => {
			if (!PROBING_MODULE.test(args.importer)) return null;
			return { path: args.path, namespace: 'stub-node' };
		});
		build.onLoad({ filter: /.*/, namespace: 'stub-node' }, () => ({
			contents: 'module.exports = {};',
			loader: 'js',
		}));
	},
};

const PLUGIN_ID = JSON.parse(fs.readFileSync("manifest.json", "utf8")).id;

// Load OBSIDIAN_PATH from .env (path to your vault's plugins folder, relative
// to $HOME, e.g. /Documents/Log/.obsidian/plugins). The plugin's own folder is
// appended automatically. Optional: without a .env, `npm run dev` just builds
// main.js in place, as it always has.
function loadEnv() {
	try {
		const raw = fs.readFileSync(".env", "utf8");
		for (const line of raw.split("\n")) {
			const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$/i);
			if (!m) continue;
			let val = m[2].trim();
			if ((val.startsWith('"') && val.endsWith('"')) ||
				(val.startsWith("'") && val.endsWith("'"))) {
				val = val.slice(1, -1);
			}
			process.env[m[1]] = val;
		}
	} catch (e) {
		if (e.code !== "ENOENT") throw e;
	}
}

// Vault name = the folder that contains .obsidian in OBSIDIAN_PATH (used to
// target the right vault when reloading via the Obsidian CLI).
function vaultName() {
	const parts = (process.env.OBSIDIAN_PATH || "").split("/").filter(Boolean);
	const i = parts.indexOf(".obsidian");
	return i > 0 ? parts[i - 1] : undefined;
}

// Ask Obsidian to hot-reload the plugin, so changes appear without a manual
// toggle. Requires the `obsidian` CLI on PATH; silently skipped if absent.
function reloadPlugin() {
	const vault = vaultName();
	// The CLI ignores vault= unless it is the first argument.
	const args = vault
		? [`vault=${vault}`, "plugin:reload", `id=${PLUGIN_ID}`]
		: ["plugin:reload", `id=${PLUGIN_ID}`];
	execFile("obsidian", args, (err, stdout) => {
		if (err) console.warn(`Skipped plugin reload: ${err.message}`);
		else console.log((stdout || "").trim() || `Reloaded: ${PLUGIN_ID}`);
	});
}

// Type-check before pushing, so a broken intermediate save (which esbuild
// happily bundles by stripping types) can't be copied in and disable the plugin
// on reload.
// Incremental, so repeat checks on a watch rebuild reuse the previous run's
// results instead of re-checking the whole project each save.
const TSC_ARGS = [
	"--skipLibCheck",
	"--incremental",
	"--tsBuildInfoFile",
	"node_modules/.cache/tsc.tsbuildinfo",
];

function typeChecks() {
	try {
		execFileSync("node_modules/.bin/tsc", TSC_ARGS, { stdio: "pipe" });
		return true;
	} catch (e) {
		const out = `${e.stdout || ""}${e.stderr || ""}`.trim();
		console.warn(`Skipped vault copy: type errors\n${out}`);
		return false;
	}
}

// A style is read when the plugin loads and never again, so a copied
// styles.css sits in the vault unseen until something reloads. Swapping the
// text of the <style> element the plugin made gets there without one, which is
// what a CSS change wants: a reload closes whatever screen is being styled.
// Told there is nothing to swap, fall back to reloading.
const STYLE_NEEDLE = 'mod-importer';

function refreshStyles() {
	const code = [
		'(async () => {',
		`const dir = app.plugins.plugins[${JSON.stringify(PLUGIN_ID)}]?.manifest.dir;`,
		'if (!dir) return "no-plugin";',
		'const styleEl = Array.from(document.head.querySelectorAll(\'style[type="text/css"]\'))',
		`.find(el => el.textContent.includes(${JSON.stringify(STYLE_NEEDLE)}));`,
		'if (!styleEl) return "no-style";',
		'styleEl.textContent = await app.vault.readRaw(dir + "/styles.css");',
		'return "ok";',
		'})()',
	].join(' ');

	const vault = vaultName();
	const args = vault ? [`vault=${vault}`, 'eval', `code=${code}`] : ['eval', `code=${code}`];

	execFile('obsidian', args, (err, stdout) => {
		if (err || !`${stdout}`.includes('ok')) {
			reloadPlugin();
			return;
		}
		console.log('Updated styles.css in place');
	});
}

// Copy the built plugin files into the vault after each rebuild, then reload.
// styles.css matters as much as main.js here: the importer's modal UI is
// entirely styled from it.
function copyToVault({ reload = true } = {}) {
	if (!process.env.OBSIDIAN_PATH || !process.env.HOME) return;
	const dest = path.join(process.env.HOME, process.env.OBSIDIAN_PATH, PLUGIN_ID);
	try {
		fs.mkdirSync(dest, { recursive: true });
		for (const file of [outfile, "manifest.json", "styles.css"]) {
			if (fs.existsSync(file)) {
				fs.copyFileSync(file, path.join(dest, path.basename(file)));
			}
		}
		console.log(`Copied plugin to ${dest}`);
		if (reload) reloadPlugin();
		else refreshStyles();
	} catch (e) {
		console.warn(`Skipped vault copy: ${e.message}`);
	}
}

// esbuild rebuilds on a change to something it bundles, and styles.css is not
// bundled: without this, editing it in a watch session never reaches the vault,
// and the change reads as a rule that had no effect. Watch the directory rather
// than the file, so a save that replaces the file keeps being noticed.
function watchCopiedFiles() {
	if (!process.env.OBSIDIAN_PATH || !process.env.HOME) return;

	const copied = ["styles.css", "manifest.json"];
	let queued;
	let reload = false;

	fs.watch(".", (event, filename) => {
		if (!copied.includes(filename)) return;

		// A style can be pushed into the running app; a manifest cannot.
		if (filename !== "styles.css") reload = true;

		// An editor saves in more than one step; copy once it has settled.
		clearTimeout(queued);
		queued = setTimeout(() => {
			copyToVault({ reload });
			reload = false;
		}, 100);
	});
}

const copyPlugin = {
	name: "copy-to-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length) return;
			if (!typeChecks()) return;
			copyToVault();
		});
	},
};

loadEnv();

let outfile = "main.js";
if (fs.existsSync('./.devtarget')) {
	outfile = path.join(fs.readFileSync('./.devtarget', 'utf8').trim(), outfile);
	console.log('Temporary output location:', outfile);
}


const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],

	// We don't need to include code to create zip files (deflate), only read them (inflate),
	// so this cuts it out and makes the final bundle smaller.
	alias: {'@zip.js/zip.js': '@zip.js/zip.js/lib/zip-no-worker-inflate.js'},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	platform: 'browser',
	treeShaking: true,
	plugins: prod
		? [stubInquirePlugin, stubOptionalNodePlugin]
		: [stubInquirePlugin, stubOptionalNodePlugin, copyPlugin],
	outfile,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	watchCopiedFiles();
}
