import { App, ButtonComponent, MarkdownRenderChild, MarkdownRenderer, MarkdownView, normalizePath, Notice, parseYaml, setIcon, Setting, SettingGroup, stringifyYaml, TFile, WorkspaceLeaf } from 'obsidian';
import { i18n } from './i18n';
import { MarkdownFileSuggest } from './markdown-file-suggest';
import { parseFrontMatterBlock } from './util';

export interface NoteTemplatePreview {
	content: string;
	label?: string;
	path?: string;
	diagnostics?: string[];
	/** False only for fatal template errors; warnings may still be imported. */
	valid?: boolean;
}

export interface NoteTemplateEditorConfig {
	template: string;
	path: string;
	titleTemplate: string;
}

export interface NoteTemplateConfiguratorOptions {
	app: App;
	/** Generated template restored when the selected file is cleared. */
	defaultTemplate: string;
	template: string;
	titleTemplate: string;
	path?: string;
	preview: (template: string, titleTemplate: string) => Promise<NoteTemplatePreview | NoteTemplatePreview[]>;
	/** Resolve to close the editor without accepting its current template. */
	cancel?: Promise<void>;
	/** Additional note-writing settings shown between the template file and preview. */
	configure?: (container: HTMLElement, previewChanged: () => void) => void;
	/** Properties generated by the importer. Their value is displayed but cannot be edited. */
	managedProperties?: () => ManagedTemplateProperty[];
}

export interface ManagedTemplateProperty {
	key: string;
	value: string;
	onKeyChange?: (key: string) => void;
}

function markdownPath(value: string): string {
	const trimmed = value.trim();
	if (!trimmed) return '';
	return normalizePath(trimmed.toLowerCase().endsWith('.md') ? trimmed : `${trimmed}.md`);
}

function previewTitle(preview: NoteTemplatePreview): string {
	if (preview.label) return preview.label;
	const name = preview.path?.slice((preview.path.lastIndexOf('/') ?? -1) + 1) ?? '';
	return name.replace(/\.md$/i, '');
}

function previewIsValid(preview: NoteTemplatePreview): boolean {
	return preview.valid ?? !preview.diagnostics?.length;
}

function propertyValueText(value: unknown): string {
	if (value === null || value === undefined) return '';
	if (typeof value === 'string') return value;
	if (typeof value === 'number' || typeof value === 'boolean' || typeof value === 'bigint') {
		return value.toString();
	}
	if (typeof value === 'object') return JSON.stringify(value) ?? '';
	return '';
}

export function propertyIcon(key: string, value: unknown): string {
	if (key.trim().toLowerCase() === 'tags') return 'lucide-tags';
	if (Array.isArray(value)) return 'lucide-list';
	if (typeof value === 'boolean') return 'lucide-check-square';
	if (typeof value === 'number') return 'lucide-binary';
	if (value && typeof value === 'object') return 'lucide-file-json';
	return 'lucide-text';
}

interface EditableProperty {
	key: string;
	value: unknown;
	managed?: boolean;
	onKeyChange?: (key: string) => void;
}

const TEMPLATE_FRONT_MATTER_PATTERN = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;
const TEMPLATE_EXPRESSION_PATTERN = /({{[\s\S]*?}}|{%[\s\S]*?%})/g;
const TEMPLATE_EXPRESSION_TOKEN = '__KNAP_TEMPLATE_EXPRESSION_';

function protectTemplateExpressions(value: string, expressions: string[]): string {
	return value.replace(TEMPLATE_EXPRESSION_PATTERN, expression => {
		const token = `${TEMPLATE_EXPRESSION_TOKEN}${expressions.length}__`;
		expressions.push(expression);
		return token;
	});
}

function restoreTemplateExpressions(value: string, expressions: string[]): string {
	return value.replace(/__KNAP_TEMPLATE_EXPRESSION_(\d+)__/g, (token, index: string) =>
		expressions[Number(index)] ?? token);
}

function transformTemplateExpressions(
	value: unknown,
	transform: (text: string) => string,
): unknown {
	if (typeof value === 'string') return transform(value);
	if (Array.isArray(value)) return value.map(item => transformTemplateExpressions(item, transform));
	if (value && typeof value === 'object') {
		return Object.fromEntries(Object.entries(value).map(([key, item]) => [
			transform(key),
			transformTemplateExpressions(item, transform),
		]));
	}
	return value;
}

function parseTemplateFrontMatter(template: string): { properties: EditableProperty[], body: string } | null {
	const match = TEMPLATE_FRONT_MATTER_PATTERN.exec(template);
	if (!match) return null;

	const expressions: string[] = [];
	try {
		const protectedYaml = protectTemplateExpressions(match[1], expressions);
		const parsed: unknown = parseYaml(protectedYaml);
		if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return null;
		const restored = transformTemplateExpressions(
			parsed,
			value => restoreTemplateExpressions(value, expressions),
		) as Record<string, unknown>;
		return {
			properties: Object.entries(restored).map(([key, value]) => ({ key, value })),
			body: template.slice(match[0].length),
		};
	}
	catch {
		return null;
	}
}

function serializeTemplate(properties: EditableProperty[], body: string): string {
	const entries = properties.filter(property => !property.managed && property.key.trim());
	if (entries.length === 0) return body;

	const expressions: string[] = [];
	const frontMatter = Object.fromEntries(entries.map(property => [property.key.trim(), property.value]));
	const protectedFrontMatter = transformTemplateExpressions(
		frontMatter,
		value => protectTemplateExpressions(value, expressions),
	);
	const yaml = stringifyYaml(protectedFrontMatter);
	return restoreTemplateExpressions(`---\n${yaml}---\n${body}`, expressions);
}

function nativeEditorTemplate(properties: EditableProperty[], body: string): string {
	const entries = properties.filter(property => property.key.trim());
	if (entries.length === 0) return body;
	const frontMatter = Object.fromEntries(entries.map(property => [property.key.trim(), property.value]));
	return `---\n${stringifyYaml(frontMatter)}---\n${body}`;
}

interface NativeMetadataEditor {
	containerEl: HTMLElement;
}

interface NativeMarkdownSubView {
	hide(): void;
	show(): void;
}

type NativeMarkdownView = MarkdownView & {
	metadataEditor: NativeMetadataEditor;
	inlineTitleEl: HTMLElement;
	currentMode: NativeMarkdownSubView;
	modes: Record<string, NativeMarkdownSubView>;
};

interface NativeTemplateEditor {
	getTemplate(): string;
	getManagedKeys(): string[];
	focus(): void;
	destroy(): Promise<void>;
}

async function createNativeTemplateEditor(
	app: App,
	container: HTMLElement,
	properties: EditableProperty[],
	body: string,
): Promise<NativeTemplateEditor> {
	// Obsidian does not export MetadataEditor, but MarkdownView is public and owns
	// the real component. A detached leaf is also how Obsidian mounts its temporary
	// mobile editor during startup. This synthetic file is never read or written.
	const Leaf = WorkspaceLeaf as unknown as new (app: App) => WorkspaceLeaf;
	const File = TFile as unknown as new (vault: App['vault'], path: string) => TFile;
	const leaf = new Leaf(app);
	const view = new MarkdownView(leaf) as NativeMarkdownView;
	view.file = new File(
		app.vault,
		normalizePath(`${app.vault.configDir}/plugins/obsidian-importer/template-preview.md`),
	);
	await leaf.open(view);

	if (view.getMode() !== 'source') {
		view.currentMode.hide();
		view.currentMode = view.modes.source as typeof view.currentMode;
		view.currentMode.show();
		view.containerEl.dataset.mode = 'source';
	}

	const initialTemplate = nativeEditorTemplate(properties, body);
	view.data = initialTemplate;
	view.setViewData(initialTemplate, true);
	view.inlineTitleEl.detach();
	container.appendChild(view.contentEl);

	const metadata = view.metadataEditor.containerEl;
	const managedProperties = properties.filter(property => property.managed);
	const lockManagedProperties = (): void => {
		const availableRows = Array.from(metadata.querySelectorAll<HTMLElement>('.metadata-property'));
		for (const [index, property] of managedProperties.entries()) {
			let row = availableRows.find(candidate =>
				candidate.dataset.importerManagedIndex === String(index)
			);
			row ??= availableRows.find(candidate =>
				candidate.dataset.propertyKey === property.key.trim().toLowerCase()
			);
			if (!row) continue;
			row.dataset.importerManagedIndex = String(index);
			row.addClass('is-generated');

			const icon = row.querySelector<HTMLElement>('.metadata-property-icon');
			icon?.setAttr('aria-disabled', true);
			const keyInput = row.querySelector<HTMLInputElement>('.metadata-property-key-input');
			if (keyInput) {
				keyInput.disabled = !property.onKeyChange;
				if (property.onKeyChange && keyInput.dataset.importerManaged !== 'true') {
					keyInput.dataset.importerManaged = 'true';
					keyInput.addEventListener('input', () => {
						property.key = keyInput.value;
						property.onKeyChange?.(keyInput.value);
					});
				}
			}

			const value = row.querySelector<HTMLElement>('.metadata-property-value');
			for (const input of Array.from(value?.querySelectorAll<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | HTMLButtonElement>('input, textarea, select, button') ?? [])) {
				input.disabled = true;
			}
			for (const editable of Array.from(value?.querySelectorAll<HTMLElement>('[contenteditable]') ?? [])) {
				editable.contentEditable = 'false';
			}
		}
	};
	lockManagedProperties();
	const observer = new MutationObserver(lockManagedProperties);
	observer.observe(metadata, { childList: true, subtree: true });
	metadata.addEventListener('mousedown', event => {
		const target = event.target as HTMLElement;
		if (!target.closest('.metadata-property.is-generated .metadata-property-icon')) return;
		event.preventDefault();
		event.stopImmediatePropagation();
	}, { capture: true });
	metadata.addEventListener('contextmenu', event => {
		const target = event.target as HTMLElement;
		if (!target.closest('.metadata-property.is-generated')) return;
		event.preventDefault();
		event.stopImmediatePropagation();
	}, { capture: true });
	metadata.addEventListener('keydown', event => {
		const target = event.target as HTMLElement;
		if (!target.closest('.metadata-property.is-generated')) return;
		if (event.key !== 'Delete' && !(event.metaKey && event.key === 'Backspace')) return;
		event.preventDefault();
		event.stopImmediatePropagation();
	}, { capture: true });

	return {
		getTemplate: () => view.getViewData(),
		getManagedKeys: () => managedProperties.map((property, index) => {
			const row = metadata.querySelector<HTMLElement>(`[data-importer-managed-index="${index}"]`);
			return row?.querySelector<HTMLInputElement>('.metadata-property-key-input')?.value
				?? property.key.trim();
		}),
		focus: () => view.editor.focus(),
		destroy: async () => {
			observer.disconnect();
			await (view as unknown as { close(): Promise<void> }).close();
		},
	};
}

function renderProperties(container: HTMLElement, properties: Record<string, unknown>): void {
	const propertyEntries = Object.entries(properties);
	if (propertyEntries.length === 0) return;

	// MetadataEditor is internal to Obsidian. Keep this read-only DOM aligned with
	// its structure so the app and the user's theme provide the real appearance.
	const metadata = container.createDiv({
		cls: 'metadata-container importer-template-properties',
		attr: { tabindex: -1, 'data-property-count': propertyEntries.length },
	});
	metadata.createDiv('metadata-error-container').toggle(false);
	const heading = metadata.createDiv({ cls: 'metadata-properties-heading', attr: { tabindex: -1 } });
	const collapse = heading.createDiv('collapse-indicator collapse-icon');
	setIcon(collapse, 'right-triangle');
	heading.createDiv({ cls: 'metadata-properties-title', text: i18n.template.headingProperties() });

	const content = metadata.createDiv('metadata-content');
	const rows = content.createDiv('metadata-properties');
	for (const [key, value] of propertyEntries) {
		const row = rows.createDiv({
			cls: 'metadata-property importer-template-property',
			attr: { tabindex: -1, 'data-property-key': key.toLowerCase() },
		});
		const keyEl = row.createDiv('metadata-property-key');
		const icon = keyEl.createSpan('metadata-property-icon');
		setIcon(icon, propertyIcon(key, value));
		keyEl.createEl('input', {
			cls: 'metadata-property-key-input',
			type: 'text',
			value: key,
			attr: { readonly: true, tabindex: -1 },
		});
		const valueEl = row.createDiv('metadata-property-value importer-template-property-value');
		valueEl.dataset.propertyType = Array.isArray(value) ? 'multitext' : typeof value;
		if (Array.isArray(value)) {
			const values = valueEl.createDiv('multi-select-container');
			for (const item of value) {
				values.createDiv({
					cls: 'multi-select-pill',
					text: propertyValueText(item),
				});
			}
		}
		else if (typeof value === 'boolean') {
			const input = valueEl.createEl('input', {
				type: 'checkbox',
				cls: 'metadata-input-checkbox',
				attr: { disabled: true, tabindex: -1 },
			});
			input.checked = value;
		}
		else if (typeof value === 'number') {
			valueEl.createEl('input', {
				type: 'number',
				cls: 'metadata-input-number',
				value: String(value),
				attr: { readonly: true, tabindex: -1 },
			});
		}
		else if (value && typeof value === 'object') {
			valueEl.createSpan({
				cls: 'metadata-property-value-item mod-unknown',
				text: propertyValueText(value),
			});
		}
		else {
			valueEl.createEl('textarea', {
				cls: 'metadata-input-text metadata-input-longtext',
				text: propertyValueText(value),
				attr: { readonly: true, tabindex: -1, rows: 1 },
			});
		}
	}
}

/** Shared Markdown-template preview and persistence screen used by every note-producing importer. */
export class NoteTemplateConfigurator {
	private template: string;
	private path: string;
	private titleTemplate: string;

	constructor(private readonly options: NoteTemplateConfiguratorOptions) {
		this.template = options.template;
		this.path = options.path ?? '';
		this.titleTemplate = options.titleTemplate;
	}

	async show(container: HTMLElement, buttonsEl: HTMLElement): Promise<NoteTemplateEditorConfig | null> {
		return await new Promise(resolve => {
			container.empty();

			let editing = false;
			let titleEditorEl: HTMLElement | null = null;
			let nativeEditor: NativeTemplateEditor | null = null;
			let managedEditorProperties: EditableProperty[] = [];
			let revision = 0;
			let templateLoadRevision = 0;
			let sampleIndex = 0;
			let samples: NoteTemplatePreview[] = [];
			let renderComponent: MarkdownRenderChild | null = null;
			let previewResizeObserver: ResizeObserver | null = null;
			let previewExpanded = false;
			let updatePreview = async (_showLoading?: boolean, _focusInvalid?: boolean): Promise<boolean> => false;
			let actionButtonEl: HTMLButtonElement | null = null;
			let settled = false;
			const finish = (result: NoteTemplateEditorConfig | null): void => {
				if (settled) return;
				settled = true;
				++revision;
				renderComponent?.unload();
				renderComponent = null;
				previewResizeObserver?.disconnect();
				if (nativeEditor) void nativeEditor.destroy();
				nativeEditor = null;
				actionButtonEl?.remove();
				resolve(result);
			};
			void this.options.cancel?.then(() => finish(null));

			// Importer settings update the rendered sample in place. Keeping the old
			// preview mounted avoids collapsing the page while a replacement loads.
			this.options.configure?.(container, () => void updatePreview(false));

			const previewGroup = new SettingGroup(container);
			const fileSetting = new Setting(previewGroup.listEl)
				.setName(i18n.template.nameTemplateFile())
				.setDesc(i18n.template.descTemplateFile());
			const pathInput = fileSetting.controlEl.createEl('input', {
				type: 'text',
				value: this.path,
				placeholder: i18n.output.placeholderTemplate(),
			});
			new MarkdownFileSuggest(this.options.app, pathInput);

			const previewSetting = new Setting(previewGroup.listEl)
				.setName(i18n.template.headingPreview())
				.setDesc(i18n.template.msgNoteTemplateIntro());
			const editButton = new ButtonComponent(previewSetting.controlEl)
				.setButtonText(i18n.template.buttonEditTemplate());
			const previewDiagnostics = previewGroup.listEl.createDiv('importer-template-diagnostics');
			const previewEl = previewGroup.listEl.createDiv('importer-template-preview');
			const preview = previewEl.createDiv('importer-template-preview-container');
			const previewNav = preview.createDiv('importer-template-preview-nav');
			const previewPath = previewNav.createDiv('importer-template-preview-path');
			const previewPathIcon = previewPath.createSpan('importer-template-preview-path-icon');
			setIcon(previewPathIcon, 'lucide-file-text');
			previewPathIcon.setAttr('aria-hidden', true);
			const previewPathTitle = previewPath.createDiv('view-header-title-container');
			const previewPathParent = previewPathTitle.createDiv('view-header-title-parent');
			const previewPathName = previewPathTitle.createDiv('view-header-title');
			previewPathTitle.createDiv({
				cls: 'view-header-title importer-template-preview-edit-label',
				text: i18n.template.labelEditImportTemplate(),
			});
			const previewNavButtons = previewNav.createDiv('importer-template-preview-nav-buttons');
			const previousButton = previewNavButtons.createEl('button');
			setIcon(previousButton, 'lucide-arrow-left');
			previousButton.setAttr('aria-label', i18n.template.buttonPreviousPreview());
			const nextButton = previewNavButtons.createEl('button');
			setIcon(nextButton, 'lucide-arrow-right');
			nextButton.setAttr('aria-label', i18n.template.buttonNextPreview());
			const previewContent = preview.createDiv('importer-template-preview-content');
			const showMoreLink = preview.createEl('a', {
				cls: 'importer-template-preview-more',
				text: i18n.template.linkShowMore(),
				href: '#',
			});
			showMoreLink.hide();
			previewNav.toggle(false);
			const clearPreview = (): void => {
				previewResizeObserver?.disconnect();
				previewContent.empty();
				previewEl.removeClass('has-more');
				showMoreLink.hide();
			};
			const hideShowMore = (): void => {
				previewEl.removeClass('has-more');
				showMoreLink.hide();
			};
			const updateShowMore = (): void => {
				const hasMore = !editing && !previewExpanded
					&& previewContent.scrollHeight > previewContent.clientHeight + 1;
				previewEl.toggleClass('has-more', hasMore);
				showMoreLink.toggle(hasMore);
			};
			const watchPreviewHeight = (rendered: HTMLElement): void => {
				previewResizeObserver?.disconnect();
				if (typeof ResizeObserver !== 'undefined') {
					previewResizeObserver = new ResizeObserver(updateShowMore);
					previewResizeObserver.observe(rendered);
				}
				updateShowMore();
				window.requestAnimationFrame?.(updateShowMore);
			};
			const collapsePreview = (): void => {
				previewExpanded = false;
				previewEl.removeClass('is-expanded');
			};
			showMoreLink.addEventListener('click', event => {
				event.preventDefault();
				previewExpanded = true;
				previewEl.addClass('is-expanded');
				hideShowMore();
			});
			const renderPreviewPath = (path: string | undefined): void => {
				const displayedPath = path?.replace(/\.md$/iu, '') ?? '';
				const segments = displayedPath.split('/').filter(Boolean);
				const name = segments.pop() ?? '';
				previewPathParent.empty();
				for (const segment of segments) {
					previewPathParent.createSpan({ cls: 'view-header-breadcrumb', text: segment });
					previewPathParent.createSpan({ cls: 'view-header-breadcrumb-separator', text: '/' });
				}
				previewPathName.setText(name);
				previewPath.setAttr('title', displayedPath);
				previewPath.toggle(Boolean(displayedPath));
			};
			const showPreviewLoading = (): void => {
				renderComponent?.unload();
				renderComponent = null;
				clearPreview();
				previewDiagnostics.empty();
				hideShowMore();
				previewPathParent.empty();
				previewPathName.empty();
				previewPath.setAttr('title', '');
				previewPath.show();
				previousButton.disabled = true;
				nextButton.disabled = true;
				previewNavButtons.show();
				previewNav.show();
				const loading = previewContent.createDiv('importer-loading importer-template-preview-loading');
				setIcon(loading.createDiv('loader-spinner'), 'loader-2');
				loading.createDiv({
					text: i18n.template.statusLoadingPreview(),
				});
			};

			const renderPreview = async (current: number): Promise<boolean> => {
				let candidateComponent: MarkdownRenderChild | null = null;
				try {
					const result = samples[sampleIndex];
					if (!result || current !== revision) return false;

					const rendered = createDiv('markdown-preview-view markdown-rendered importer-template-rendered-note');
					const parsed = parseFrontMatterBlock(result.content);
					rendered.createDiv({
						cls: 'inline-title',
						text: previewTitle(result),
						attr: { contenteditable: false, tabindex: -1 },
					});
					renderProperties(rendered, parsed?.frontMatter ?? {});
					const markdown = rendered.createDiv('importer-template-markdown');
					candidateComponent = new MarkdownRenderChild(rendered);
					candidateComponent.load();
					await MarkdownRenderer.render(
						this.options.app,
						parsed?.body ?? result.content,
						markdown,
						result.path ?? '',
						candidateComponent,
					);
					if (current !== revision) {
						candidateComponent.unload();
						return false;
					}

					renderComponent?.unload();
					renderComponent = candidateComponent;
					candidateComponent = null;
					clearPreview();
					previewContent.append(rendered);
					watchPreviewHeight(rendered);
					renderPreviewPath(result.path);
					previousButton.disabled = false;
					nextButton.disabled = false;
					previewNavButtons.toggle(samples.length > 1);
					previewNav.show();
					previewDiagnostics.empty();
					for (const diagnostic of result.diagnostics ?? []) {
						previewDiagnostics.createDiv({ text: diagnostic });
					}
					return previewIsValid(result);
				}
				catch (error) {
					candidateComponent?.unload();
					if (current !== revision) return false;
					clearPreview();
					previewNav.hide();
					previewDiagnostics.setText(error instanceof Error ? error.message : String(error));
					return false;
				}
			};

			const setEditing = (value: boolean): void => {
				editing = value;
				previewEl.toggleClass('is-editing', value);
				previewPath.toggleClass('is-editing', value);
				if (value) hideShowMore();
				if (value) previewPath.show();
				editButton.setButtonText(value
					? i18n.template.buttonSaveTemplate()
					: i18n.template.buttonEditTemplate());
				if (value) editButton.setCta();
				else editButton.removeCta();
			};

			const startEditing = async (): Promise<void> => {
				const current = ++revision;
				renderComponent?.unload();
				renderComponent = null;
				if (nativeEditor) void nativeEditor.destroy();
				nativeEditor = null;
				clearPreview();
				previewDiagnostics.empty();
				previousButton.disabled = true;
				nextButton.disabled = true;
				previewNavButtons.show();
				previewNav.show();
				const parsedTemplate = parseTemplateFrontMatter(this.template);
				managedEditorProperties = (this.options.managedProperties?.() ?? [])
					.map(property => ({ ...property, managed: true }));
				const managedKeys = new Set(managedEditorProperties.map(property => property.key.trim().toLowerCase()));
				const editorProperties = [
					...managedEditorProperties,
					...(parsedTemplate?.properties ?? []).filter(property =>
						!managedKeys.has(property.key.trim().toLowerCase())
					),
				];
				const rendered = previewContent.createDiv('importer-template-rendered-note importer-template-editing-note');
				titleEditorEl = rendered.createDiv({
					cls: 'inline-title',
					text: this.titleTemplate,
					attr: {
						contenteditable: true,
						'aria-label': i18n.template.nameTitle(),
						spellcheck: false,
					},
				});
				titleEditorEl.addEventListener('keydown', event => {
					if (event.key !== 'Enter') return;
					event.preventDefault();
				});
				setEditing(true);
				editButton.setDisabled(true);
				actionButtonEl?.setAttr('disabled', true);
				try {
					const candidate = await createNativeTemplateEditor(
						this.options.app,
						rendered.createDiv('importer-template-native-editor'),
						editorProperties,
						parsedTemplate?.body ?? this.template,
					);
					if (current !== revision || !editing) {
						await candidate.destroy();
						return;
					}
					nativeEditor = candidate;
					nativeEditor.focus();
				}
				catch (error) {
					if (current !== revision) return;
					previewDiagnostics.setText(error instanceof Error ? error.message : String(error));
					setEditing(false);
				}
				finally {
					editButton.setDisabled(false);
					actionButtonEl?.removeAttribute('disabled');
				}
			};

			const finishEditing = (): boolean => {
				if (!editing || !nativeEditor) return false;
				this.titleTemplate = titleEditorEl?.textContent?.trim() || '{{title}}';
				const nativeTemplate = nativeEditor.getTemplate();
				const parsedTemplate = parseTemplateFrontMatter(nativeTemplate);
				const currentManagedKeys = nativeEditor.getManagedKeys();
				for (const [index, property] of managedEditorProperties.entries()) {
					const key = currentManagedKeys[index]?.trim();
					if (!key) continue;
					property.key = key;
					property.onKeyChange?.(key);
				}
				const managedKeys = new Set(currentManagedKeys.map(key => key.trim().toLowerCase()));
				const properties = (parsedTemplate?.properties ?? []).filter(property =>
					!managedKeys.has(property.key.trim().toLowerCase())
				);
				const editedTemplate = serializeTemplate(properties, parsedTemplate?.body ?? nativeTemplate);
				if (editedTemplate !== this.template) {
					this.template = editedTemplate;
					this.path = '';
					pathInput.value = '';
				}
				void nativeEditor.destroy();
				nativeEditor = null;
				titleEditorEl = null;
				managedEditorProperties = [];
				++templateLoadRevision;
				setEditing(false);
				return true;
			};

			updatePreview = async (showLoading = true, focusInvalid = false): Promise<boolean> => {
				const current = ++revision;
				if (showLoading) showPreviewLoading();
				try {
					const result = await this.options.preview(this.template, this.titleTemplate);
					if (current !== revision) return false;
					samples = Array.isArray(result) ? result : [result];
					sampleIndex = Math.min(sampleIndex, Math.max(0, samples.length - 1));
					if (focusInvalid) {
						const invalidIndex = samples.findIndex(sample => !previewIsValid(sample));
						if (invalidIndex >= 0) sampleIndex = invalidIndex;
					}
					const rendered = await renderPreview(current);
					const allValid = samples.every(previewIsValid);
					return rendered && allValid;
				}
				catch (error) {
					if (current !== revision) return false;
					clearPreview();
					previewNav.hide();
					previewDiagnostics.setText(error instanceof Error ? error.message : String(error));
					return false;
				}
			};

			editButton.onClick(() => {
				if (!editing) {
					void startEditing();
					return;
				}

				if (finishEditing()) void updatePreview();
			});

			previousButton.addEventListener('click', () => {
				if (samples.length < 2) return;
				sampleIndex = (sampleIndex - 1 + samples.length) % samples.length;
				collapsePreview();
				void renderPreview(++revision);
			});
			nextButton.addEventListener('click', () => {
				if (samples.length < 2) return;
				sampleIndex = (sampleIndex + 1) % samples.length;
				collapsePreview();
				void renderPreview(++revision);
			});

			const loadTemplate = async (): Promise<void> => {
				const current = ++templateLoadRevision;
				const path = markdownPath(pathInput.value);
				const hadTemplatePath = this.path !== '';
				this.path = '';
				const resetTemplate = async (): Promise<void> => {
					if (!hadTemplatePath) return;
					this.template = this.options.defaultTemplate;
					setEditing(false);
					if (nativeEditor) void nativeEditor.destroy();
					nativeEditor = null;
					titleEditorEl = null;
					await updatePreview();
				};
				if (!path) {
					await resetTemplate();
					return;
				}
				const file = this.options.app.vault.getAbstractFileByPath(path)
					?? this.options.app.vault.getAbstractFileByPathInsensitive(path);
				// Partial paths while typing are expected. Suggestions trigger this same
				// event once they have placed a complete path in the input.
				if (!(file instanceof TFile) || file.extension.toLowerCase() !== 'md') {
					await resetTemplate();
					return;
				}
				try {
					const loaded = await this.options.app.vault.cachedRead(file);
					if (current !== templateLoadRevision) return;
					this.template = loaded;
					this.path = file.path;
					pathInput.value = file.path;
					setEditing(false);
					if (nativeEditor) void nativeEditor.destroy();
					nativeEditor = null;
					titleEditorEl = null;
					await updatePreview();
				}
				catch (error) {
					if (current !== templateLoadRevision) return;
					new Notice(error instanceof Error ? error.message : String(error));
				}
			};
			pathInput.addEventListener('input', () => void loadTemplate());

			actionButtonEl = buttonsEl.createEl('button', { cls: 'mod-cta', text: i18n.modal.buttonImport() }, button => {
				button.addEventListener('click', () => {
					finishEditing();
					void updatePreview(true, true).then(valid => {
						if (!valid) return;
						finish({
							template: this.template,
							path: this.path,
							titleTemplate: this.titleTemplate,
						});
					});
				});
			});

			void updatePreview();
		});
	}
}
