name: CI
on:
  push:
    branches: ["master"]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install modules
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint:check

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm run build
